development:
  adapter: postgresql
  encoding: unicode
  database: christen_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: christen_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: christen_production
  pool: 5
